const db=require("../db"),crypto=require("crypto"),policy=require("./policySuppressionEngine");
const MODEL=process.env.OPENAI_MODEL||"gpt-5.6-luna";
const schema={type:"object",additionalProperties:false,properties:{decision:{type:"string",enum:["SEND","WAIT","DIGITAL_ONLY","DO_NOTHING"]},experience:{type:"string",enum:["EXECUTIVE_LETTER","PERSONALIZED_POSTCARD","REVOPS_DIAGNOSTIC_POSTCARD","EXECUTIVE_GIFT_BOX","NONE"]},confidence:{type:"number",minimum:0,maximum:1},recommended_spend:{type:"number",minimum:0},intent_score:{type:"number",minimum:0,maximum:100},physical_intervention_score:{type:"number",minimum:0,maximum:100},evidence:{type:"array",items:{type:"string"}},risks:{type:"array",items:{type:"string"}},reasoning_summary:{type:"string"},message:{type:"string"},next_action:{type:"string"}},required:["decision","experience","confidence","recommended_spend","intent_score","physical_intervention_score","evidence","risks","reasoning_summary","message","next_action"]};
function fallback({account,contact,signals,policyResult}){const intent=Number(account.intent_score||0),physical=Number(account.physical_intervention_score||0);let decision="DO_NOTHING",experience="NONE",spend=0;if(!policyResult.passed)decision="DO_NOTHING";else if(intent>=85&&physical>=80){decision="SEND";experience=contact?.persona_type==="executive"?"EXECUTIVE_LETTER":"REVOPS_DIAGNOSTIC_POSTCARD";spend=experience==="EXECUTIVE_LETTER"?35:12}else if(intent>=65)decision="DIGITAL_ONLY";else if(intent>=45)decision="WAIT";return{decision,experience,confidence:.78,recommended_spend:spend,intent_score:intent,physical_intervention_score:physical,evidence:signals.map(s=>`${s.signal_name} (${s.strength})`),risks:policyResult.reasons,reasoning_summary:`Intent ${intent} and physical intervention score ${physical} drive ${decision}.`,message:decision==="SEND"?`A tailored executive touch for ${contact?.name||"the prospect"}.` :"",next_action:decision==="SEND"?"Approve fulfillment":"Continue digital monitoring"}}
async function evaluate({org,accountId,contactId,cost=12,campaignId}){
 const get=async(table,id)=>db.mode==="postgres"?(await db.query(`SELECT * FROM ${table} WHERE id=$1 AND organization_id=$2`,[id,org])).rows[0]:db.first(table,x=>x.id===id&&x.organization_id===org);
 const account=await get("accounts",accountId),contact=await get("contacts",contactId); if(!account||!contact)throw new Error("account/contact not found");
 const signals=db.mode==="postgres"?(await db.query("SELECT * FROM signals WHERE organization_id=$1 AND account_id=$2 ORDER BY occurred_at DESC LIMIT 25",[org,accountId])).rows:db.all("signals",x=>x.organization_id===org&&x.account_id===accountId);
 const campaign=campaignId?await get("campaigns",campaignId):null; const policyResult=await policy.evaluate({org,account,contact,cost,campaign});
 let result=fallback({account,contact,signals,policyResult});
 if(process.env.OPENAI_API_KEY){try{const body={model:MODEL,input:[{role:"system",content:[{type:"input_text",text:"You are IntentPost Intelligence. Decide whether a physical GTM intervention is justified. Consider buying intent, account value, relationship stage, opportunity value, cost, risk, and policy. You may choose DO_NOTHING."}]},{role:"user",content:[{type:"input_text",text:JSON.stringify({account,contact,signals,policy:policyResult})}]}],text:{format:{type:"json_schema",name:"intentpost_decision",schema,strict:true}}};const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify(body)});if(r.ok){const x=await r.json(),txt=x.output_text||x.output?.flatMap(o=>o.content||[]).find(c=>c.text)?.text;if(txt)result=JSON.parse(txt)}}catch(e){result.ai_error=e.message}}
 const audit={id:crypto.randomUUID(),organization_id:org,account_id:accountId,contact_id:contactId,decision:result,model:MODEL};
 if(db.mode==="postgres")await db.query("INSERT INTO ai_decision_audits(id,organization_id,account_id,contact_id,decision,model) VALUES($1,$2,$3,$4,$5,$6)",[audit.id,org,accountId,contactId,JSON.stringify(result),MODEL]);else db.insert("ai_decision_audits",audit);
 return {...result,policy:policyResult,audit_id:audit.id};
}
module.exports={evaluate,schema};
